### ISSUE TITLE
[EPIC] Audit/Update Gem to work with the initial implementation of GlimmerJS

### ISSUE THREAD

**Issue by mswanson** [koryteg/glimmer-rails#6]
Using the `ember-cli-rails` gem as a basis, we want to get a basic glimmer app running inside rails. Below is a list of the high-level task that need to be completed to get this working. Not all these files _necessarily_ need to be changed but each should be reviewed to make sure it won't cause issues since we are switching out the full ember stack for just glimmer. 

Most of the tasks have been broken up based on directory but can be tackled in any order or as small groups (e.g. audit/update `/lib/ember_cli/command.rb` and update the spec in `/spec/lib/ember_cli/command_spec.rb`

### `ember-cli-rails-addon`
- [ ] Audit/Document how the addon interops with this gem and what functionality we need
- [ ] Figure out if we can still use that addon or if we'll need to do that work another way
	- seems unlike we can use the addon since Glimmer doesn't currently support add-ons
	- probably will need to create a generic npm package that glimmer can use to stub the behavior until official add-on support lands
 
### `/` - root directory
- [ ] Add `CONTRIBUTORS`
	- invite more maintainers
- [ ] Audit/Update `.ruby-version`
	- [ ] what ruby version should we be using?
- [ ] Audit/Update `.travis.yaml` and get the gem running on TravisCI
- [ ] Audit/Update `Appraisals` 
	- Do we need to test other versions of Rails?
- [ ] Audit/Update the documentation
	- [ ] `CHANGELOG`
	- [ ] `CONTRIBUTIING`
	- [ ] `RELEASING`
	- [ ] `UPGRADING`
	- [ ] `README`
		- make sure to give credit to the amazing team of contributors on `ember-cli-rails` and that this gem is largely a fork of that one.
- [ ] Audit/Update `gemfile` 
	- we should probably be targeting Rails 5.0.x
- [ ] Audit/Update `ember-cli-rails.gemspec`

### `/app`
- [ ] Audit/Update Ember Controller
- [ ] Audit/Update EmberRailsHelper
- [ ] Audit/Update Ember View `ember_cli/ember/index.html.erb`

### `/bin`
- [ ] Audit/Update `setup` script
- [ ] Audit/Update `setup_ember`

### `/lib`
- [ ] Audit/Update `ember-cli-rails.rb` 
	- verify against recommended CLI commands for Glimmer
- [ ] Audit/Update files in `lib/ember_cli`
	- [ ] `deploy/file.rb`
	- [ ] `app.rb`
	- [ ] `build_monitor.rb`
	- [ ] `command.rb`
	- [ ] `configuration.rb`
	- [ ] `ember_constraint.rb`
	- [ ] `engine.rb`
	- [ ] `errors.rb`
	- [ ] `helpers.rb`
	- [ ] `path_set.rb`
	- [ ] `rout_helpers.rb`
	- [ ] `runner.rb`
	- [ ] `shell.rb`
	- [ ] `version.rb`
- [ ] Audit/Update generators 
	- [ ] For Heroku in `generators/ember/heroku`
	- [ ] For init in  `generators/ember/init`
- [ ] Audit/Update Rake tasks in `ember-cli/rake`

### `/spec`
- [ ] Audit/Update dummy app
- [ ] Audit/Update feature specs
- [ ] Audit/Update request specs
- [ ] Audit/Update `spec_helper`
- [ ] Audit/Update `/sepc/lib/eber_cli`
	- [ ] `dummy/file_spec.rb`
	- [ ] `app_spec.rb`
	- [ ] `build_monitor_spec.rb`
	- [ ] `command_spec.rb`
	- [ ] `ember_contraint_spec.rb`
	- [ ] `helpers_spec.rb`
	- [ ] `path_spec.rb`
	- [ ] `runner_spec.rb`
